### ISSUE TITLE
Incorrect information about npm install

### ISSUE THREAD

**Issue by Khobalt** [flaviocopes/website-content#23]
You need to pass --save or --save-dev to npm install in order for the package.json and package-lock.json to be updated.

**Comment by flaviocopes** [comment]
Hi, `--save` happens by default since npm 5, more than 2 years ago. You don't need it, so you don't need to type it. People still use it, not sure why. They probably don't know this fact.

`--save-dev` is still needed for dev dependencies, but I don't know which post you are referring to so I can't check if I did some error in that.
